/**
 * Shared English strings. Plain nested strings only — this whole folder can be
 * serialized to `lt.json` and mirrored as `en.json` / `ru.json` later.
 */
type Testimonial = { name: string; country: string; quote: string; source: string };

const testimonials: Testimonial[] = [
  {
    name: "Anna",
    country: "Germany",
    quote: "The silence, the fjord and the hot tub under the northern lights made this a place we did not want to leave.",
    source: "Guest book",
  },
  {
    name: "James",
    country: "United Kingdom",
    quote: "Breakfast arrived warm, the cabin felt completely private, and the hosts knew exactly where the snow was best.",
    source: "Guest book",
  },
  {
    name: "Sofia",
    country: "Denmark",
    quote: "Beautifully simple, warm and thoughtful. Looking through the skylight from bed was unforgettable.",
    source: "Guest book",
  },
  {
    name: "Noah",
    country: "Canada",
    quote: "A rare place that feels remote without feeling difficult. We would return in every season.",
    source: "Guest book",
  },
  {
    name: "Mia",
    country: "Netherlands",
    quote: "The sauna, cold tub and dark valley sky were exactly why we came north.",
    source: "Guest book",
  },
  {
    name: "Luca",
    country: "Italy",
    quote: "Old timber, excellent beds and a host who answered every question without making the place feel managed.",
    source: "Guest book",
  },
];

export const common = {
  brand: "Mánahlíð",
  tagline: "Tröllaskagi · Iceland",
  cta: {
    book: "Book",
    checkDates: "Check available dates",
    more: "Learn more",
    openMap: "Open in map",
    contactUs: "Contact us",
    allStays: "All rooms & cabins",
  },
  nav: {
    home: "Home",
    about: "The house",
    rules: "Practical",
    stays: "Rooms & cabins",
    standard: "House rooms",
    terrace: "Ridge rooms",
    cottage: "Private cabins",
    restobar: "Breakfast",
    banquet: "Gatherings",
    sauna: "Sauna",
    vouchers: "Gift stays",
    contacts: "Find us",
    more: "More",
    site: "Site",
  },
  labels: {
    priceFrom: "From",
    size: "Size",
    guests: "Guests",
    upTo: "up to",
    guestsLower: "guests",
    bedsLower: "beds",
    perNight: "per night",
    address: "Address",
    amenities: "Amenities",
    contacts: "Contacts",
    breadcrumb: "Breadcrumb",
    otherStays: "Other accommodation options",
  },
  stays: {
    availabilityTitle: "Available dates",
    availabilityLead:
      "Choose your check-in and check-out dates. Occupied days are marked and cannot be selected.",
    checkin: "Check-in",
    checkout: "Check-out",
    occupied: "Occupied",
    occupiedDayLabel: "Occupied day — cannot be booked",
    available: "Available",
    selected: "Selected",
    nights: "nights",
    night: "night",
    nightsMany: "nights",
    pickDates: "Choose dates",
    clearDates: "Clear",
    noOccupied: "All dates are currently available.",
    loading: "Loading…",
    errorTitle: "Failed to load apartments",
    errorText:
      "The booking system is currently unreachable. Please try again or contact us directly.",
    retry: "Try again",
    emptyTitle: "No available properties at the moment",
    emptyText:
      "The list will be updated soon. For dates and availability, please contact us directly.",
    priceOnRequest: "Price on request",
    pickProperty: "Choose accommodation",
    galleryTitle: "Gallery",
  },
  booking: {
    adults: "Adults",
    children: "Children",
    infants: "Infants",
    extras: "Extra services",
    perPerson: "per person per night",
    perChild: "per child per night",
    flatPerDay: "per night",
    nights: "Nights",
    nightlyRate: "Rate per night",
    stayTotal: "Subtotal",
    extrasTotal: "Extras total",
    total: "Total",
    calculating: "Calculating price…",
    pickDatesPrompt: "Choose your check-in and check-out dates — we'll show the price right away.",
    unavailable: "These dates are no longer available. Please choose other dates.",
    tooManyGuests: "Too many guests for this accommodation. Please reduce the number of guests.",
    badRequest: "Please check the dates and number of guests.",
    notFound: "This accommodation could no longer be found.",
    genericError: "Failed to calculate the price. Please try again.",
    submitSoon: "Booking confirmation coming soon",
    contactTitle: "Your contact details",
    name: "Full name",
    email: "Email",
    phone: "Phone",
    bic: "Bank BIC (optional)",
    nameError: "Enter your full name (at least 2 characters).",
    emailError: "Enter a valid email address.",
    phoneError: "Enter a phone number (at least 5 characters).",
    bicError: "BIC can be up to 20 characters.",
    submit: "Book",
    submitting: "Sending…",
    datesUnavailable: "Sorry, these dates were just taken. Please choose other dates.",
    submitError: "Failed to create the booking. Please try again.",
    needQuote: "Choose your dates and wait for the price — then you'll be able to book.",
    companyToggle: "Booking on behalf of a company",
    companyTitle: "Company details",
    companyName: "Company name",
    companyCode: "Company code",
    companyVat: "VAT code (optional)",
    companyAddress: "Company address",
    companyNameError: "Enter the company name.",
    companyCodeError: "Enter the company code.",
    companyAddressError: "Enter the company address.",
    consentPrefix: "I have read and agree to the",
    consentTerms: "terms of service",
    consentAnd: "and",
    consentPrivacy: "privacy policy",
    datesLoading: "Checking availability…",
    dialogTitle: "Check availability",
    dialogDescription:
      "You are booking directly on the Mánahlíð website. Payment is by bank transfer — we show the details right after your booking.",
    stayLabel: "Accommodation",
    noCommissionNote: "Direct booking — no agents, no Booking.com commission.",
    consentError: "Please confirm your agreement to the terms to continue.",
  },
  footer: {
    intro: "Six rooms and eight cabins on the Tröllaskagi peninsula.",
    rights: "Direct booking. No intermediaries.",
  },
  availabilityBand: {
    eyebrow: "Available dates",
    title: "Check available dates",
    lead: "Choose your check-in and check-out dates — you'll instantly see how many apartments of each type are available and how much they cost.",
    guests: "Guests",
    pickDates: "Choose your check-in and check-out dates.",
    checking: "Checking available dates…",
    freeOne: "available",
    freeFew: "available",
    freeMany: "available",
    none: "None available",
    ofTotal: "of",
    priceFor: "for",
    error: "Failed to check available dates. Please try again.",
    retry: "Try again",
    reset: "Clear dates",
  },
  categories: {
    standard: "House rooms",
    terrace: "Ridge rooms",
    cottage: "Private cabins",
  },
  categoryCard: {
    viewOptions: "View options",
    optionsOne: "option",
    optionsFew: "options",
    optionsMany: "options",
  },
  search: {
    eyebrow: "66°N · North Iceland",
    title: "A farm at the end of the fjord.",
    lead: "Six rooms and eight cabins on the Tröllaskagi peninsula.",
    datesLabel: "Dates",
    datesPlaceholder: "Check-in — check-out",
    guestsLabel: "Guests",
    submit: "Search",
    clear: "Clear",
    done: "Done",
    nightOne: "night",
    nightFew: "nights",
    nightMany: "nights",
    adults: "Adults",
    adultsHint: "13+",
    children: "Children",
    childrenHint: "2–12 yrs",
    infants: "Infants",
    infantsHint: "under 2",
    adultOne: "adult",
    adultFew: "adults",
    adultMany: "adults",
    childOne: "child",
    childFew: "children",
    childMany: "children",
    infantOne: "infant",
    infantFew: "infants",
    infantMany: "infants",
    needDates: "Choose dates",
    checkIn: "Check-in",
    checkOut: "Check-out",
    nightsLabel: "Nights",

  },
  results: {
    seoTitle: "Available rooms — Mánahlíð",
    seoDescription:
      "Rooms and cabins available at Mánahlíð in North Iceland. Book directly, without intermediaries.",
    eyebrow: "Available rooms",
    title: "Available on your dates",
    missingDates: "Choose check-in and check-out dates and we'll show what is available.",
    loading: "Checking availability…",
    loadingTitle: "One moment…",
    loadingText: "We are looking for available rooms and cabins for your dates.",
    empty: "No rooms available on these dates",
    emptyHint: "Try other dates or reduce the number of guests.",
    error: "Could not check availability.",
    retry: "Try again",
    forStay: "for the whole stay",
    perNight: "per night",
    openGallery: "View photos",
    closeGallery: "Close",
    prev: "Previous",
    next: "Next",
    foundOne: "room available",
    foundFew: "rooms available",
    foundMany: "rooms available",
    moreInfo: "More",
    lessInfo: "Close",
    detailsTitle: "Room details",
    amenitiesTitle: "Room amenities",
  },
  testimonials: {
    eyebrow: "Booking.com reviews",
    title: "What guests say",
    prev: "Previous reviews",
    next: "Next reviews",
    items: testimonials,
  },
};
