/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as BanquetHallRouteImport } from './routes/banquet-hall'
import { Route as CabinRouteImport } from './routes/cabin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnRouteRouteImport } from './routes/en/route'
import { Route as GiftVouchersRouteImport } from './routes/gift-vouchers'
import { Route as HomeV2RouteImport } from './routes/home-v2'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as SaunaRouteImport } from './routes/sauna'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutHouseRulesRouteImport } from './routes/about.house-rules'
import { Route as ApartamentaiSplatRouteImport } from './routes/apartamentai.$'
import { Route as ApiTrackViewRouteImport } from './routes/api/track-view'
import { Route as ApieSplatRouteImport } from './routes/apie.$'
import { Route as BanketineSaleSplatRouteImport } from './routes/banketine-sale.$'
import { Route as BookingConfirmedRouteImport } from './routes/booking.confirmed'
import { Route as DovanuKuponaiSplatRouteImport } from './routes/dovanu-kuponai.$'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnAvailabilityRouteImport } from './routes/en/availability'
import { Route as EnBanquetHallRouteImport } from './routes/en/banquet-hall'
import { Route as EnCabinRouteImport } from './routes/en/cabin'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as EnGiftVouchersRouteImport } from './routes/en/gift-vouchers'
import { Route as EnHomeV2RouteImport } from './routes/en/home-v2'
import { Route as EnPrivacyPolicyRouteImport } from './routes/en/privacy-policy'
import { Route as EnRestaurantRouteImport } from './routes/en/restaurant'
import { Route as EnSaunaRouteImport } from './routes/en/sauna'
import { Route as EnStaysRouteImport } from './routes/en/stays'
import { Route as EnTermsRouteImport } from './routes/en/terms'
import { Route as KontaktaiSplatRouteImport } from './routes/kontaktai.$'
import { Route as LaisviKambariaiSplatRouteImport } from './routes/laisvi-kambariai.$'
import { Route as NamelisSplatRouteImport } from './routes/namelis.$'
import { Route as PrivatumoPolitikaSplatRouteImport } from './routes/privatumo-politika.$'
import { Route as RestobarasSplatRouteImport } from './routes/restobaras.$'
import { Route as RezervacijaSplatRouteImport } from './routes/rezervacija.$'
import { Route as StaysIndexRouteImport } from './routes/stays.index'
import { Route as StaysPropertyIdRouteImport } from './routes/stays.$propertyId'
import { Route as StaysStandardRouteImport } from './routes/stays.standard'
import { Route as StaysWithTerraceRouteImport } from './routes/stays.with-terrace'
import { Route as TaisyklesSplatRouteImport } from './routes/taisykles.$'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminContractsRouteImport } from './routes/_authenticated/admin.contracts'
import { Route as AuthenticatedAdminExpensesRouteImport } from './routes/_authenticated/admin.expenses'
import { Route as AuthenticatedAdminHousekeepingRouteImport } from './routes/_authenticated/admin.housekeeping'
import { Route as AuthenticatedAdminInquiriesRouteImport } from './routes/_authenticated/admin.inquiries'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin.pricing'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedStaffIdRouteImport } from './routes/_authenticated/staff.$id'
import { Route as ApiAssistantChatRouteImport } from './routes/api/assistant/chat'
import { Route as ApiPublicIcalSyncRouteImport } from './routes/api/public/ical-sync'
import { Route as ApiPublicNotificationsCronRouteImport } from './routes/api/public/notifications-cron'
import { Route as EnAboutIndexRouteImport } from './routes/en/about.index'
import { Route as EnAboutHouseRulesRouteImport } from './routes/en/about.house-rules'
import { Route as EnBookingConfirmedRouteImport } from './routes/en/booking.confirmed'
import { Route as EnStaysIndexRouteImport } from './routes/en/stays.index'
import { Route as EnStaysPropertyIdRouteImport } from './routes/en/stays.$propertyId'
import { Route as EnStaysStandardRouteImport } from './routes/en/stays.standard'
import { Route as EnStaysWithTerraceRouteImport } from './routes/en/stays.with-terrace'
import { Route as StaysTypeCategorySlugRouteImport } from './routes/stays.type.$categorySlug'
import { Route as AuthenticatedAdminBookingsIndexRouteImport } from './routes/_authenticated/admin.bookings.index'
import { Route as AuthenticatedAdminBookingsIdRouteImport } from './routes/_authenticated/admin.bookings.$id'
import { Route as AuthenticatedAdminBookingsNewRouteImport } from './routes/_authenticated/admin.bookings.new'
import { Route as AuthenticatedAdminPropertiesIndexRouteImport } from './routes/_authenticated/admin.properties.index'
import { Route as AuthenticatedAdminPropertiesNewRouteImport } from './routes/_authenticated/admin.properties.new'
import { Route as ApiPublicV1AvailabilityRouteImport } from './routes/api/public/v1/availability'
import { Route as ApiPublicV1BookingsRouteImport } from './routes/api/public/v1/bookings'
import { Route as ApiPublicV1LegalRouteImport } from './routes/api/public/v1/legal'
import { Route as ApiPublicV1PaymentDetailsRouteImport } from './routes/api/public/v1/payment-details'
import { Route as ApiPublicV1PropertiesRouteImport } from './routes/api/public/v1/properties'
import { Route as ApiPublicV1QuoteRouteImport } from './routes/api/public/v1/quote'
import { Route as ApiStaffV1RoomsRouteImport } from './routes/api/staff/v1/rooms'
import { Route as EnStaysTypeCategorySlugRouteImport } from './routes/en/stays.type.$categorySlug'
import { Route as AuthenticatedAdminPropertiesIdEditRouteImport } from './routes/_authenticated/admin.properties.$id.edit'
import { Route as ApiPublicV1BookingsBookingNumberRouteImport } from './routes/api/public/v1/bookings.$bookingNumber'
import { Route as ApiPublicV1PropertiesIdRouteImport } from './routes/api/public/v1/properties.$id'
import { Route as ApiStaffV1RoomsIdAssignRouteImport } from './routes/api/staff/v1/rooms.$id.assign'
import { Route as ApiStaffV1RoomsIdCommentsRouteImport } from './routes/api/staff/v1/rooms.$id.comments'
import { Route as ApiStaffV1RoomsIdIssueRouteImport } from './routes/api/staff/v1/rooms.$id.issue'
import { Route as ApiStaffV1RoomsIdStatusRouteImport } from './routes/api/staff/v1/rooms.$id.status'
import { Route as ApiStaffV1RoomsIdUnassignRouteImport } from './routes/api/staff/v1/rooms.$id.unassign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const BanquetHallRoute = BanquetHallRouteImport.update({
  id: '/banquet-hall',
  path: '/banquet-hall',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinRoute = CabinRouteImport.update({
  id: '/cabin',
  path: '/cabin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRouteRoute = EnRouteRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftVouchersRoute = GiftVouchersRouteImport.update({
  id: '/gift-vouchers',
  path: '/gift-vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeV2Route = HomeV2RouteImport.update({
  id: '/home-v2',
  path: '/home-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const SaunaRoute = SaunaRouteImport.update({
  id: '/sauna',
  path: '/sauna',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const AboutHouseRulesRoute = AboutHouseRulesRouteImport.update({
  id: '/house-rules',
  path: '/house-rules',
  getParentRoute: () => AboutRoute,
} as any)
const ApartamentaiSplatRoute = ApartamentaiSplatRouteImport.update({
  id: '/apartamentai/$',
  path: '/apartamentai/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackViewRoute = ApiTrackViewRouteImport.update({
  id: '/api/track-view',
  path: '/api/track-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApieSplatRoute = ApieSplatRouteImport.update({
  id: '/apie/$',
  path: '/apie/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BanketineSaleSplatRoute = BanketineSaleSplatRouteImport.update({
  id: '/banketine-sale/$',
  path: '/banketine-sale/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking/confirmed',
  path: '/booking/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const DovanuKuponaiSplatRoute = DovanuKuponaiSplatRouteImport.update({
  id: '/dovanu-kuponai/$',
  path: '/dovanu-kuponai/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnAvailabilityRoute = EnAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnBanquetHallRoute = EnBanquetHallRouteImport.update({
  id: '/banquet-hall',
  path: '/banquet-hall',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnCabinRoute = EnCabinRouteImport.update({
  id: '/cabin',
  path: '/cabin',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnGiftVouchersRoute = EnGiftVouchersRouteImport.update({
  id: '/gift-vouchers',
  path: '/gift-vouchers',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnHomeV2Route = EnHomeV2RouteImport.update({
  id: '/home-v2',
  path: '/home-v2',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnPrivacyPolicyRoute = EnPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnRestaurantRoute = EnRestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnSaunaRoute = EnSaunaRouteImport.update({
  id: '/sauna',
  path: '/sauna',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnStaysRoute = EnStaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnTermsRoute = EnTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => EnRouteRoute,
} as any)
const KontaktaiSplatRoute = KontaktaiSplatRouteImport.update({
  id: '/kontaktai/$',
  path: '/kontaktai/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LaisviKambariaiSplatRoute = LaisviKambariaiSplatRouteImport.update({
  id: '/laisvi-kambariai/$',
  path: '/laisvi-kambariai/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NamelisSplatRoute = NamelisSplatRouteImport.update({
  id: '/namelis/$',
  path: '/namelis/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatumoPolitikaSplatRoute = PrivatumoPolitikaSplatRouteImport.update({
  id: '/privatumo-politika/$',
  path: '/privatumo-politika/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RestobarasSplatRoute = RestobarasSplatRouteImport.update({
  id: '/restobaras/$',
  path: '/restobaras/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RezervacijaSplatRoute = RezervacijaSplatRouteImport.update({
  id: '/rezervacija/$',
  path: '/rezervacija/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysIndexRoute = StaysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaysRoute,
} as any)
const StaysPropertyIdRoute = StaysPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => StaysRoute,
} as any)
const StaysStandardRoute = StaysStandardRouteImport.update({
  id: '/standard',
  path: '/standard',
  getParentRoute: () => StaysRoute,
} as any)
const StaysWithTerraceRoute = StaysWithTerraceRouteImport.update({
  id: '/with-terrace',
  path: '/with-terrace',
  getParentRoute: () => StaysRoute,
} as any)
const TaisyklesSplatRoute = TaisyklesSplatRouteImport.update({
  id: '/taisykles/$',
  path: '/taisykles/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContractsRoute =
  AuthenticatedAdminContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpensesRoute =
  AuthenticatedAdminExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHousekeepingRoute =
  AuthenticatedAdminHousekeepingRouteImport.update({
    id: '/housekeeping',
    path: '/housekeeping',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInquiriesRoute =
  AuthenticatedAdminInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffIdRoute = AuthenticatedStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const ApiAssistantChatRoute = ApiAssistantChatRouteImport.update({
  id: '/api/assistant/chat',
  path: '/api/assistant/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIcalSyncRoute = ApiPublicIcalSyncRouteImport.update({
  id: '/api/public/ical-sync',
  path: '/api/public/ical-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationsCronRoute =
  ApiPublicNotificationsCronRouteImport.update({
    id: '/api/public/notifications-cron',
    path: '/api/public/notifications-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnAboutIndexRoute = EnAboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnAboutRoute,
} as any)
const EnAboutHouseRulesRoute = EnAboutHouseRulesRouteImport.update({
  id: '/house-rules',
  path: '/house-rules',
  getParentRoute: () => EnAboutRoute,
} as any)
const EnBookingConfirmedRoute = EnBookingConfirmedRouteImport.update({
  id: '/booking/confirmed',
  path: '/booking/confirmed',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnStaysIndexRoute = EnStaysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnStaysRoute,
} as any)
const EnStaysPropertyIdRoute = EnStaysPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => EnStaysRoute,
} as any)
const EnStaysStandardRoute = EnStaysStandardRouteImport.update({
  id: '/standard',
  path: '/standard',
  getParentRoute: () => EnStaysRoute,
} as any)
const EnStaysWithTerraceRoute = EnStaysWithTerraceRouteImport.update({
  id: '/with-terrace',
  path: '/with-terrace',
  getParentRoute: () => EnStaysRoute,
} as any)
const StaysTypeCategorySlugRoute = StaysTypeCategorySlugRouteImport.update({
  id: '/type/$categorySlug',
  path: '/type/$categorySlug',
  getParentRoute: () => StaysRoute,
} as any)
const AuthenticatedAdminBookingsIndexRoute =
  AuthenticatedAdminBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsIdRoute =
  AuthenticatedAdminBookingsIdRouteImport.update({
    id: '/bookings/$id',
    path: '/bookings/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsNewRoute =
  AuthenticatedAdminBookingsNewRouteImport.update({
    id: '/bookings/new',
    path: '/bookings/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesIndexRoute =
  AuthenticatedAdminPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesNewRoute =
  AuthenticatedAdminPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicV1AvailabilityRoute = ApiPublicV1AvailabilityRouteImport.update({
  id: '/api/public/v1/availability',
  path: '/api/public/v1/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1BookingsRoute = ApiPublicV1BookingsRouteImport.update({
  id: '/api/public/v1/bookings',
  path: '/api/public/v1/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1LegalRoute = ApiPublicV1LegalRouteImport.update({
  id: '/api/public/v1/legal',
  path: '/api/public/v1/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PaymentDetailsRoute =
  ApiPublicV1PaymentDetailsRouteImport.update({
    id: '/api/public/v1/payment-details',
    path: '/api/public/v1/payment-details',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1PropertiesRoute = ApiPublicV1PropertiesRouteImport.update({
  id: '/api/public/v1/properties',
  path: '/api/public/v1/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1QuoteRoute = ApiPublicV1QuoteRouteImport.update({
  id: '/api/public/v1/quote',
  path: '/api/public/v1/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffV1RoomsRoute = ApiStaffV1RoomsRouteImport.update({
  id: '/api/staff/v1/rooms',
  path: '/api/staff/v1/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const EnStaysTypeCategorySlugRoute = EnStaysTypeCategorySlugRouteImport.update({
  id: '/type/$categorySlug',
  path: '/type/$categorySlug',
  getParentRoute: () => EnStaysRoute,
} as any)
const AuthenticatedAdminPropertiesIdEditRoute =
  AuthenticatedAdminPropertiesIdEditRouteImport.update({
    id: '/properties/$id/edit',
    path: '/properties/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicV1BookingsBookingNumberRoute =
  ApiPublicV1BookingsBookingNumberRouteImport.update({
    id: '/$bookingNumber',
    path: '/$bookingNumber',
    getParentRoute: () => ApiPublicV1BookingsRoute,
  } as any)
const ApiPublicV1PropertiesIdRoute = ApiPublicV1PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1PropertiesRoute,
} as any)
const ApiStaffV1RoomsIdAssignRoute = ApiStaffV1RoomsIdAssignRouteImport.update({
  id: '/$id/assign',
  path: '/$id/assign',
  getParentRoute: () => ApiStaffV1RoomsRoute,
} as any)
const ApiStaffV1RoomsIdCommentsRoute =
  ApiStaffV1RoomsIdCommentsRouteImport.update({
    id: '/$id/comments',
    path: '/$id/comments',
    getParentRoute: () => ApiStaffV1RoomsRoute,
  } as any)
const ApiStaffV1RoomsIdIssueRoute = ApiStaffV1RoomsIdIssueRouteImport.update({
  id: '/$id/issue',
  path: '/$id/issue',
  getParentRoute: () => ApiStaffV1RoomsRoute,
} as any)
const ApiStaffV1RoomsIdStatusRoute = ApiStaffV1RoomsIdStatusRouteImport.update({
  id: '/$id/status',
  path: '/$id/status',
  getParentRoute: () => ApiStaffV1RoomsRoute,
} as any)
const ApiStaffV1RoomsIdUnassignRoute =
  ApiStaffV1RoomsIdUnassignRouteImport.update({
    id: '/$id/unassign',
    path: '/$id/unassign',
    getParentRoute: () => ApiStaffV1RoomsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRouteRouteWithChildren
  '/about': typeof AboutRouteWithChildren
  '/auth': typeof AuthRoute
  '/availability': typeof AvailabilityRoute
  '/banquet-hall': typeof BanquetHallRoute
  '/cabin': typeof CabinRoute
  '/contact': typeof ContactRoute
  '/gift-vouchers': typeof GiftVouchersRoute
  '/home-v2': typeof HomeV2Route
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRoute
  '/sauna': typeof SaunaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stays': typeof StaysRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/about/house-rules': typeof AboutHouseRulesRoute
  '/apartamentai/$': typeof ApartamentaiSplatRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/apie/$': typeof ApieSplatRoute
  '/banketine-sale/$': typeof BanketineSaleSplatRoute
  '/booking/confirmed': typeof BookingConfirmedRoute
  '/dovanu-kuponai/$': typeof DovanuKuponaiSplatRoute
  '/en/about': typeof EnAboutRouteWithChildren
  '/en/availability': typeof EnAvailabilityRoute
  '/en/banquet-hall': typeof EnBanquetHallRoute
  '/en/cabin': typeof EnCabinRoute
  '/en/contact': typeof EnContactRoute
  '/en/gift-vouchers': typeof EnGiftVouchersRoute
  '/en/home-v2': typeof EnHomeV2Route
  '/en/privacy-policy': typeof EnPrivacyPolicyRoute
  '/en/restaurant': typeof EnRestaurantRoute
  '/en/sauna': typeof EnSaunaRoute
  '/en/stays': typeof EnStaysRouteWithChildren
  '/en/terms': typeof EnTermsRoute
  '/kontaktai/$': typeof KontaktaiSplatRoute
  '/laisvi-kambariai/$': typeof LaisviKambariaiSplatRoute
  '/namelis/$': typeof NamelisSplatRoute
  '/privatumo-politika/$': typeof PrivatumoPolitikaSplatRoute
  '/restobaras/$': typeof RestobarasSplatRoute
  '/rezervacija/$': typeof RezervacijaSplatRoute
  '/stays/$propertyId': typeof StaysPropertyIdRoute
  '/stays/standard': typeof StaysStandardRoute
  '/stays/with-terrace': typeof StaysWithTerraceRoute
  '/taisykles/$': typeof TaisyklesSplatRoute
  '/about/': typeof AboutIndexRoute
  '/en/': typeof EnIndexRoute
  '/stays/': typeof StaysIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/housekeeping': typeof AuthenticatedAdminHousekeepingRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/public/ical-sync': typeof ApiPublicIcalSyncRoute
  '/api/public/notifications-cron': typeof ApiPublicNotificationsCronRoute
  '/en/about/house-rules': typeof EnAboutHouseRulesRoute
  '/en/booking/confirmed': typeof EnBookingConfirmedRoute
  '/en/stays/$propertyId': typeof EnStaysPropertyIdRoute
  '/en/stays/standard': typeof EnStaysStandardRoute
  '/en/stays/with-terrace': typeof EnStaysWithTerraceRoute
  '/stays/type/$categorySlug': typeof StaysTypeCategorySlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/en/about/': typeof EnAboutIndexRoute
  '/en/stays/': typeof EnStaysIndexRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/admin/properties/new': typeof AuthenticatedAdminPropertiesNewRoute
  '/api/public/v1/availability': typeof ApiPublicV1AvailabilityRoute
  '/api/public/v1/bookings': typeof ApiPublicV1BookingsRouteWithChildren
  '/api/public/v1/legal': typeof ApiPublicV1LegalRoute
  '/api/public/v1/payment-details': typeof ApiPublicV1PaymentDetailsRoute
  '/api/public/v1/properties': typeof ApiPublicV1PropertiesRouteWithChildren
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/api/staff/v1/rooms': typeof ApiStaffV1RoomsRouteWithChildren
  '/en/stays/type/$categorySlug': typeof EnStaysTypeCategorySlugRoute
  '/admin/bookings/': typeof AuthenticatedAdminBookingsIndexRoute
  '/admin/properties/': typeof AuthenticatedAdminPropertiesIndexRoute
  '/admin/properties/$id/edit': typeof AuthenticatedAdminPropertiesIdEditRoute
  '/api/public/v1/bookings/$bookingNumber': typeof ApiPublicV1BookingsBookingNumberRoute
  '/api/public/v1/properties/$id': typeof ApiPublicV1PropertiesIdRoute
  '/api/staff/v1/rooms/$id/assign': typeof ApiStaffV1RoomsIdAssignRoute
  '/api/staff/v1/rooms/$id/comments': typeof ApiStaffV1RoomsIdCommentsRoute
  '/api/staff/v1/rooms/$id/issue': typeof ApiStaffV1RoomsIdIssueRoute
  '/api/staff/v1/rooms/$id/status': typeof ApiStaffV1RoomsIdStatusRoute
  '/api/staff/v1/rooms/$id/unassign': typeof ApiStaffV1RoomsIdUnassignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/availability': typeof AvailabilityRoute
  '/banquet-hall': typeof BanquetHallRoute
  '/cabin': typeof CabinRoute
  '/contact': typeof ContactRoute
  '/gift-vouchers': typeof GiftVouchersRoute
  '/home-v2': typeof HomeV2Route
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRoute
  '/sauna': typeof SaunaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about/house-rules': typeof AboutHouseRulesRoute
  '/apartamentai/$': typeof ApartamentaiSplatRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/apie/$': typeof ApieSplatRoute
  '/banketine-sale/$': typeof BanketineSaleSplatRoute
  '/booking/confirmed': typeof BookingConfirmedRoute
  '/dovanu-kuponai/$': typeof DovanuKuponaiSplatRoute
  '/en/availability': typeof EnAvailabilityRoute
  '/en/banquet-hall': typeof EnBanquetHallRoute
  '/en/cabin': typeof EnCabinRoute
  '/en/contact': typeof EnContactRoute
  '/en/gift-vouchers': typeof EnGiftVouchersRoute
  '/en/home-v2': typeof EnHomeV2Route
  '/en/privacy-policy': typeof EnPrivacyPolicyRoute
  '/en/restaurant': typeof EnRestaurantRoute
  '/en/sauna': typeof EnSaunaRoute
  '/en/terms': typeof EnTermsRoute
  '/kontaktai/$': typeof KontaktaiSplatRoute
  '/laisvi-kambariai/$': typeof LaisviKambariaiSplatRoute
  '/namelis/$': typeof NamelisSplatRoute
  '/privatumo-politika/$': typeof PrivatumoPolitikaSplatRoute
  '/restobaras/$': typeof RestobarasSplatRoute
  '/rezervacija/$': typeof RezervacijaSplatRoute
  '/stays/$propertyId': typeof StaysPropertyIdRoute
  '/stays/standard': typeof StaysStandardRoute
  '/stays/with-terrace': typeof StaysWithTerraceRoute
  '/taisykles/$': typeof TaisyklesSplatRoute
  '/about': typeof AboutIndexRoute
  '/en': typeof EnIndexRoute
  '/stays': typeof StaysIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/admin/housekeeping': typeof AuthenticatedAdminHousekeepingRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/public/ical-sync': typeof ApiPublicIcalSyncRoute
  '/api/public/notifications-cron': typeof ApiPublicNotificationsCronRoute
  '/en/about/house-rules': typeof EnAboutHouseRulesRoute
  '/en/booking/confirmed': typeof EnBookingConfirmedRoute
  '/en/stays/$propertyId': typeof EnStaysPropertyIdRoute
  '/en/stays/standard': typeof EnStaysStandardRoute
  '/en/stays/with-terrace': typeof EnStaysWithTerraceRoute
  '/stays/type/$categorySlug': typeof StaysTypeCategorySlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/en/about': typeof EnAboutIndexRoute
  '/en/stays': typeof EnStaysIndexRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/admin/properties/new': typeof AuthenticatedAdminPropertiesNewRoute
  '/api/public/v1/availability': typeof ApiPublicV1AvailabilityRoute
  '/api/public/v1/bookings': typeof ApiPublicV1BookingsRouteWithChildren
  '/api/public/v1/legal': typeof ApiPublicV1LegalRoute
  '/api/public/v1/payment-details': typeof ApiPublicV1PaymentDetailsRoute
  '/api/public/v1/properties': typeof ApiPublicV1PropertiesRouteWithChildren
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/api/staff/v1/rooms': typeof ApiStaffV1RoomsRouteWithChildren
  '/en/stays/type/$categorySlug': typeof EnStaysTypeCategorySlugRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsIndexRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesIndexRoute
  '/admin/properties/$id/edit': typeof AuthenticatedAdminPropertiesIdEditRoute
  '/api/public/v1/bookings/$bookingNumber': typeof ApiPublicV1BookingsBookingNumberRoute
  '/api/public/v1/properties/$id': typeof ApiPublicV1PropertiesIdRoute
  '/api/staff/v1/rooms/$id/assign': typeof ApiStaffV1RoomsIdAssignRoute
  '/api/staff/v1/rooms/$id/comments': typeof ApiStaffV1RoomsIdCommentsRoute
  '/api/staff/v1/rooms/$id/issue': typeof ApiStaffV1RoomsIdIssueRoute
  '/api/staff/v1/rooms/$id/status': typeof ApiStaffV1RoomsIdStatusRoute
  '/api/staff/v1/rooms/$id/unassign': typeof ApiStaffV1RoomsIdUnassignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/en': typeof EnRouteRouteWithChildren
  '/about': typeof AboutRouteWithChildren
  '/auth': typeof AuthRoute
  '/availability': typeof AvailabilityRoute
  '/banquet-hall': typeof BanquetHallRoute
  '/cabin': typeof CabinRoute
  '/contact': typeof ContactRoute
  '/gift-vouchers': typeof GiftVouchersRoute
  '/home-v2': typeof HomeV2Route
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRoute
  '/sauna': typeof SaunaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stays': typeof StaysRouteWithChildren
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/about/house-rules': typeof AboutHouseRulesRoute
  '/apartamentai/$': typeof ApartamentaiSplatRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/apie/$': typeof ApieSplatRoute
  '/banketine-sale/$': typeof BanketineSaleSplatRoute
  '/booking/confirmed': typeof BookingConfirmedRoute
  '/dovanu-kuponai/$': typeof DovanuKuponaiSplatRoute
  '/en/about': typeof EnAboutRouteWithChildren
  '/en/availability': typeof EnAvailabilityRoute
  '/en/banquet-hall': typeof EnBanquetHallRoute
  '/en/cabin': typeof EnCabinRoute
  '/en/contact': typeof EnContactRoute
  '/en/gift-vouchers': typeof EnGiftVouchersRoute
  '/en/home-v2': typeof EnHomeV2Route
  '/en/privacy-policy': typeof EnPrivacyPolicyRoute
  '/en/restaurant': typeof EnRestaurantRoute
  '/en/sauna': typeof EnSaunaRoute
  '/en/stays': typeof EnStaysRouteWithChildren
  '/en/terms': typeof EnTermsRoute
  '/kontaktai/$': typeof KontaktaiSplatRoute
  '/laisvi-kambariai/$': typeof LaisviKambariaiSplatRoute
  '/namelis/$': typeof NamelisSplatRoute
  '/privatumo-politika/$': typeof PrivatumoPolitikaSplatRoute
  '/restobaras/$': typeof RestobarasSplatRoute
  '/rezervacija/$': typeof RezervacijaSplatRoute
  '/stays/$propertyId': typeof StaysPropertyIdRoute
  '/stays/standard': typeof StaysStandardRoute
  '/stays/with-terrace': typeof StaysWithTerraceRoute
  '/taisykles/$': typeof TaisyklesSplatRoute
  '/about/': typeof AboutIndexRoute
  '/en/': typeof EnIndexRoute
  '/stays/': typeof StaysIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/contracts': typeof AuthenticatedAdminContractsRoute
  '/_authenticated/admin/expenses': typeof AuthenticatedAdminExpensesRoute
  '/_authenticated/admin/housekeeping': typeof AuthenticatedAdminHousekeepingRoute
  '/_authenticated/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/staff/$id': typeof AuthenticatedStaffIdRoute
  '/api/assistant/chat': typeof ApiAssistantChatRoute
  '/api/public/ical-sync': typeof ApiPublicIcalSyncRoute
  '/api/public/notifications-cron': typeof ApiPublicNotificationsCronRoute
  '/en/about/house-rules': typeof EnAboutHouseRulesRoute
  '/en/booking/confirmed': typeof EnBookingConfirmedRoute
  '/en/stays/$propertyId': typeof EnStaysPropertyIdRoute
  '/en/stays/standard': typeof EnStaysStandardRoute
  '/en/stays/with-terrace': typeof EnStaysWithTerraceRoute
  '/stays/type/$categorySlug': typeof StaysTypeCategorySlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/en/about/': typeof EnAboutIndexRoute
  '/en/stays/': typeof EnStaysIndexRoute
  '/_authenticated/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/_authenticated/admin/bookings/new': typeof AuthenticatedAdminBookingsNewRoute
  '/_authenticated/admin/properties/new': typeof AuthenticatedAdminPropertiesNewRoute
  '/api/public/v1/availability': typeof ApiPublicV1AvailabilityRoute
  '/api/public/v1/bookings': typeof ApiPublicV1BookingsRouteWithChildren
  '/api/public/v1/legal': typeof ApiPublicV1LegalRoute
  '/api/public/v1/payment-details': typeof ApiPublicV1PaymentDetailsRoute
  '/api/public/v1/properties': typeof ApiPublicV1PropertiesRouteWithChildren
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/api/staff/v1/rooms': typeof ApiStaffV1RoomsRouteWithChildren
  '/en/stays/type/$categorySlug': typeof EnStaysTypeCategorySlugRoute
  '/_authenticated/admin/bookings/': typeof AuthenticatedAdminBookingsIndexRoute
  '/_authenticated/admin/properties/': typeof AuthenticatedAdminPropertiesIndexRoute
  '/_authenticated/admin/properties/$id/edit': typeof AuthenticatedAdminPropertiesIdEditRoute
  '/api/public/v1/bookings/$bookingNumber': typeof ApiPublicV1BookingsBookingNumberRoute
  '/api/public/v1/properties/$id': typeof ApiPublicV1PropertiesIdRoute
  '/api/staff/v1/rooms/$id/assign': typeof ApiStaffV1RoomsIdAssignRoute
  '/api/staff/v1/rooms/$id/comments': typeof ApiStaffV1RoomsIdCommentsRoute
  '/api/staff/v1/rooms/$id/issue': typeof ApiStaffV1RoomsIdIssueRoute
  '/api/staff/v1/rooms/$id/status': typeof ApiStaffV1RoomsIdStatusRoute
  '/api/staff/v1/rooms/$id/unassign': typeof ApiStaffV1RoomsIdUnassignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/about'
    | '/auth'
    | '/availability'
    | '/banquet-hall'
    | '/cabin'
    | '/contact'
    | '/gift-vouchers'
    | '/home-v2'
    | '/privacy-policy'
    | '/reset-password'
    | '/restaurant'
    | '/sauna'
    | '/sitemap.xml'
    | '/stays'
    | '/terms'
    | '/admin'
    | '/staff'
    | '/about/house-rules'
    | '/apartamentai/$'
    | '/api/track-view'
    | '/apie/$'
    | '/banketine-sale/$'
    | '/booking/confirmed'
    | '/dovanu-kuponai/$'
    | '/en/about'
    | '/en/availability'
    | '/en/banquet-hall'
    | '/en/cabin'
    | '/en/contact'
    | '/en/gift-vouchers'
    | '/en/home-v2'
    | '/en/privacy-policy'
    | '/en/restaurant'
    | '/en/sauna'
    | '/en/stays'
    | '/en/terms'
    | '/kontaktai/$'
    | '/laisvi-kambariai/$'
    | '/namelis/$'
    | '/privatumo-politika/$'
    | '/restobaras/$'
    | '/rezervacija/$'
    | '/stays/$propertyId'
    | '/stays/standard'
    | '/stays/with-terrace'
    | '/taisykles/$'
    | '/about/'
    | '/en/'
    | '/stays/'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/contracts'
    | '/admin/expenses'
    | '/admin/housekeeping'
    | '/admin/inquiries'
    | '/admin/pricing'
    | '/admin/settings'
    | '/staff/$id'
    | '/api/assistant/chat'
    | '/api/public/ical-sync'
    | '/api/public/notifications-cron'
    | '/en/about/house-rules'
    | '/en/booking/confirmed'
    | '/en/stays/$propertyId'
    | '/en/stays/standard'
    | '/en/stays/with-terrace'
    | '/stays/type/$categorySlug'
    | '/admin/'
    | '/staff/'
    | '/en/about/'
    | '/en/stays/'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/properties/new'
    | '/api/public/v1/availability'
    | '/api/public/v1/bookings'
    | '/api/public/v1/legal'
    | '/api/public/v1/payment-details'
    | '/api/public/v1/properties'
    | '/api/public/v1/quote'
    | '/api/staff/v1/rooms'
    | '/en/stays/type/$categorySlug'
    | '/admin/bookings/'
    | '/admin/properties/'
    | '/admin/properties/$id/edit'
    | '/api/public/v1/bookings/$bookingNumber'
    | '/api/public/v1/properties/$id'
    | '/api/staff/v1/rooms/$id/assign'
    | '/api/staff/v1/rooms/$id/comments'
    | '/api/staff/v1/rooms/$id/issue'
    | '/api/staff/v1/rooms/$id/status'
    | '/api/staff/v1/rooms/$id/unassign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/availability'
    | '/banquet-hall'
    | '/cabin'
    | '/contact'
    | '/gift-vouchers'
    | '/home-v2'
    | '/privacy-policy'
    | '/reset-password'
    | '/restaurant'
    | '/sauna'
    | '/sitemap.xml'
    | '/terms'
    | '/about/house-rules'
    | '/apartamentai/$'
    | '/api/track-view'
    | '/apie/$'
    | '/banketine-sale/$'
    | '/booking/confirmed'
    | '/dovanu-kuponai/$'
    | '/en/availability'
    | '/en/banquet-hall'
    | '/en/cabin'
    | '/en/contact'
    | '/en/gift-vouchers'
    | '/en/home-v2'
    | '/en/privacy-policy'
    | '/en/restaurant'
    | '/en/sauna'
    | '/en/terms'
    | '/kontaktai/$'
    | '/laisvi-kambariai/$'
    | '/namelis/$'
    | '/privatumo-politika/$'
    | '/restobaras/$'
    | '/rezervacija/$'
    | '/stays/$propertyId'
    | '/stays/standard'
    | '/stays/with-terrace'
    | '/taisykles/$'
    | '/about'
    | '/en'
    | '/stays'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/contracts'
    | '/admin/expenses'
    | '/admin/housekeeping'
    | '/admin/inquiries'
    | '/admin/pricing'
    | '/admin/settings'
    | '/staff/$id'
    | '/api/assistant/chat'
    | '/api/public/ical-sync'
    | '/api/public/notifications-cron'
    | '/en/about/house-rules'
    | '/en/booking/confirmed'
    | '/en/stays/$propertyId'
    | '/en/stays/standard'
    | '/en/stays/with-terrace'
    | '/stays/type/$categorySlug'
    | '/admin'
    | '/staff'
    | '/en/about'
    | '/en/stays'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/properties/new'
    | '/api/public/v1/availability'
    | '/api/public/v1/bookings'
    | '/api/public/v1/legal'
    | '/api/public/v1/payment-details'
    | '/api/public/v1/properties'
    | '/api/public/v1/quote'
    | '/api/staff/v1/rooms'
    | '/en/stays/type/$categorySlug'
    | '/admin/bookings'
    | '/admin/properties'
    | '/admin/properties/$id/edit'
    | '/api/public/v1/bookings/$bookingNumber'
    | '/api/public/v1/properties/$id'
    | '/api/staff/v1/rooms/$id/assign'
    | '/api/staff/v1/rooms/$id/comments'
    | '/api/staff/v1/rooms/$id/issue'
    | '/api/staff/v1/rooms/$id/status'
    | '/api/staff/v1/rooms/$id/unassign'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/en'
    | '/about'
    | '/auth'
    | '/availability'
    | '/banquet-hall'
    | '/cabin'
    | '/contact'
    | '/gift-vouchers'
    | '/home-v2'
    | '/privacy-policy'
    | '/reset-password'
    | '/restaurant'
    | '/sauna'
    | '/sitemap.xml'
    | '/stays'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/staff'
    | '/about/house-rules'
    | '/apartamentai/$'
    | '/api/track-view'
    | '/apie/$'
    | '/banketine-sale/$'
    | '/booking/confirmed'
    | '/dovanu-kuponai/$'
    | '/en/about'
    | '/en/availability'
    | '/en/banquet-hall'
    | '/en/cabin'
    | '/en/contact'
    | '/en/gift-vouchers'
    | '/en/home-v2'
    | '/en/privacy-policy'
    | '/en/restaurant'
    | '/en/sauna'
    | '/en/stays'
    | '/en/terms'
    | '/kontaktai/$'
    | '/laisvi-kambariai/$'
    | '/namelis/$'
    | '/privatumo-politika/$'
    | '/restobaras/$'
    | '/rezervacija/$'
    | '/stays/$propertyId'
    | '/stays/standard'
    | '/stays/with-terrace'
    | '/taisykles/$'
    | '/about/'
    | '/en/'
    | '/stays/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/contracts'
    | '/_authenticated/admin/expenses'
    | '/_authenticated/admin/housekeeping'
    | '/_authenticated/admin/inquiries'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/settings'
    | '/_authenticated/staff/$id'
    | '/api/assistant/chat'
    | '/api/public/ical-sync'
    | '/api/public/notifications-cron'
    | '/en/about/house-rules'
    | '/en/booking/confirmed'
    | '/en/stays/$propertyId'
    | '/en/stays/standard'
    | '/en/stays/with-terrace'
    | '/stays/type/$categorySlug'
    | '/_authenticated/admin/'
    | '/_authenticated/staff/'
    | '/en/about/'
    | '/en/stays/'
    | '/_authenticated/admin/bookings/$id'
    | '/_authenticated/admin/bookings/new'
    | '/_authenticated/admin/properties/new'
    | '/api/public/v1/availability'
    | '/api/public/v1/bookings'
    | '/api/public/v1/legal'
    | '/api/public/v1/payment-details'
    | '/api/public/v1/properties'
    | '/api/public/v1/quote'
    | '/api/staff/v1/rooms'
    | '/en/stays/type/$categorySlug'
    | '/_authenticated/admin/bookings/'
    | '/_authenticated/admin/properties/'
    | '/_authenticated/admin/properties/$id/edit'
    | '/api/public/v1/bookings/$bookingNumber'
    | '/api/public/v1/properties/$id'
    | '/api/staff/v1/rooms/$id/assign'
    | '/api/staff/v1/rooms/$id/comments'
    | '/api/staff/v1/rooms/$id/issue'
    | '/api/staff/v1/rooms/$id/status'
    | '/api/staff/v1/rooms/$id/unassign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EnRouteRoute: typeof EnRouteRouteWithChildren
  AboutRoute: typeof AboutRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvailabilityRoute: typeof AvailabilityRoute
  BanquetHallRoute: typeof BanquetHallRoute
  CabinRoute: typeof CabinRoute
  ContactRoute: typeof ContactRoute
  GiftVouchersRoute: typeof GiftVouchersRoute
  HomeV2Route: typeof HomeV2Route
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantRoute: typeof RestaurantRoute
  SaunaRoute: typeof SaunaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaysRoute: typeof StaysRouteWithChildren
  TermsRoute: typeof TermsRoute
  ApartamentaiSplatRoute: typeof ApartamentaiSplatRoute
  ApiTrackViewRoute: typeof ApiTrackViewRoute
  ApieSplatRoute: typeof ApieSplatRoute
  BanketineSaleSplatRoute: typeof BanketineSaleSplatRoute
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  DovanuKuponaiSplatRoute: typeof DovanuKuponaiSplatRoute
  KontaktaiSplatRoute: typeof KontaktaiSplatRoute
  LaisviKambariaiSplatRoute: typeof LaisviKambariaiSplatRoute
  NamelisSplatRoute: typeof NamelisSplatRoute
  PrivatumoPolitikaSplatRoute: typeof PrivatumoPolitikaSplatRoute
  RestobarasSplatRoute: typeof RestobarasSplatRoute
  RezervacijaSplatRoute: typeof RezervacijaSplatRoute
  TaisyklesSplatRoute: typeof TaisyklesSplatRoute
  ApiAssistantChatRoute: typeof ApiAssistantChatRoute
  ApiPublicIcalSyncRoute: typeof ApiPublicIcalSyncRoute
  ApiPublicNotificationsCronRoute: typeof ApiPublicNotificationsCronRoute
  ApiPublicV1AvailabilityRoute: typeof ApiPublicV1AvailabilityRoute
  ApiPublicV1BookingsRoute: typeof ApiPublicV1BookingsRouteWithChildren
  ApiPublicV1LegalRoute: typeof ApiPublicV1LegalRoute
  ApiPublicV1PaymentDetailsRoute: typeof ApiPublicV1PaymentDetailsRoute
  ApiPublicV1PropertiesRoute: typeof ApiPublicV1PropertiesRouteWithChildren
  ApiPublicV1QuoteRoute: typeof ApiPublicV1QuoteRoute
  ApiStaffV1RoomsRoute: typeof ApiStaffV1RoomsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banquet-hall': {
      id: '/banquet-hall'
      path: '/banquet-hall'
      fullPath: '/banquet-hall'
      preLoaderRoute: typeof BanquetHallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabin': {
      id: '/cabin'
      path: '/cabin'
      fullPath: '/cabin'
      preLoaderRoute: typeof CabinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-vouchers': {
      id: '/gift-vouchers'
      path: '/gift-vouchers'
      fullPath: '/gift-vouchers'
      preLoaderRoute: typeof GiftVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-v2': {
      id: '/home-v2'
      path: '/home-v2'
      fullPath: '/home-v2'
      preLoaderRoute: typeof HomeV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sauna': {
      id: '/sauna'
      path: '/sauna'
      fullPath: '/sauna'
      preLoaderRoute: typeof SaunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/house-rules': {
      id: '/about/house-rules'
      path: '/house-rules'
      fullPath: '/about/house-rules'
      preLoaderRoute: typeof AboutHouseRulesRouteImport
      parentRoute: typeof AboutRoute
    }
    '/apartamentai/$': {
      id: '/apartamentai/$'
      path: '/apartamentai/$'
      fullPath: '/apartamentai/$'
      preLoaderRoute: typeof ApartamentaiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-view': {
      id: '/api/track-view'
      path: '/api/track-view'
      fullPath: '/api/track-view'
      preLoaderRoute: typeof ApiTrackViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apie/$': {
      id: '/apie/$'
      path: '/apie/$'
      fullPath: '/apie/$'
      preLoaderRoute: typeof ApieSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banketine-sale/$': {
      id: '/banketine-sale/$'
      path: '/banketine-sale/$'
      fullPath: '/banketine-sale/$'
      preLoaderRoute: typeof BanketineSaleSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmed': {
      id: '/booking/confirmed'
      path: '/booking/confirmed'
      fullPath: '/booking/confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dovanu-kuponai/$': {
      id: '/dovanu-kuponai/$'
      path: '/dovanu-kuponai/$'
      fullPath: '/dovanu-kuponai/$'
      preLoaderRoute: typeof DovanuKuponaiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/availability': {
      id: '/en/availability'
      path: '/availability'
      fullPath: '/en/availability'
      preLoaderRoute: typeof EnAvailabilityRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/banquet-hall': {
      id: '/en/banquet-hall'
      path: '/banquet-hall'
      fullPath: '/en/banquet-hall'
      preLoaderRoute: typeof EnBanquetHallRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/cabin': {
      id: '/en/cabin'
      path: '/cabin'
      fullPath: '/en/cabin'
      preLoaderRoute: typeof EnCabinRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/gift-vouchers': {
      id: '/en/gift-vouchers'
      path: '/gift-vouchers'
      fullPath: '/en/gift-vouchers'
      preLoaderRoute: typeof EnGiftVouchersRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/home-v2': {
      id: '/en/home-v2'
      path: '/home-v2'
      fullPath: '/en/home-v2'
      preLoaderRoute: typeof EnHomeV2RouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/privacy-policy': {
      id: '/en/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/en/privacy-policy'
      preLoaderRoute: typeof EnPrivacyPolicyRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/restaurant': {
      id: '/en/restaurant'
      path: '/restaurant'
      fullPath: '/en/restaurant'
      preLoaderRoute: typeof EnRestaurantRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/sauna': {
      id: '/en/sauna'
      path: '/sauna'
      fullPath: '/en/sauna'
      preLoaderRoute: typeof EnSaunaRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/stays': {
      id: '/en/stays'
      path: '/stays'
      fullPath: '/en/stays'
      preLoaderRoute: typeof EnStaysRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/terms': {
      id: '/en/terms'
      path: '/terms'
      fullPath: '/en/terms'
      preLoaderRoute: typeof EnTermsRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/kontaktai/$': {
      id: '/kontaktai/$'
      path: '/kontaktai/$'
      fullPath: '/kontaktai/$'
      preLoaderRoute: typeof KontaktaiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laisvi-kambariai/$': {
      id: '/laisvi-kambariai/$'
      path: '/laisvi-kambariai/$'
      fullPath: '/laisvi-kambariai/$'
      preLoaderRoute: typeof LaisviKambariaiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namelis/$': {
      id: '/namelis/$'
      path: '/namelis/$'
      fullPath: '/namelis/$'
      preLoaderRoute: typeof NamelisSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatumo-politika/$': {
      id: '/privatumo-politika/$'
      path: '/privatumo-politika/$'
      fullPath: '/privatumo-politika/$'
      preLoaderRoute: typeof PrivatumoPolitikaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restobaras/$': {
      id: '/restobaras/$'
      path: '/restobaras/$'
      fullPath: '/restobaras/$'
      preLoaderRoute: typeof RestobarasSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezervacija/$': {
      id: '/rezervacija/$'
      path: '/rezervacija/$'
      fullPath: '/rezervacija/$'
      preLoaderRoute: typeof RezervacijaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/': {
      id: '/stays/'
      path: '/'
      fullPath: '/stays/'
      preLoaderRoute: typeof StaysIndexRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/$propertyId': {
      id: '/stays/$propertyId'
      path: '/$propertyId'
      fullPath: '/stays/$propertyId'
      preLoaderRoute: typeof StaysPropertyIdRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/standard': {
      id: '/stays/standard'
      path: '/standard'
      fullPath: '/stays/standard'
      preLoaderRoute: typeof StaysStandardRouteImport
      parentRoute: typeof StaysRoute
    }
    '/stays/with-terrace': {
      id: '/stays/with-terrace'
      path: '/with-terrace'
      fullPath: '/stays/with-terrace'
      preLoaderRoute: typeof StaysWithTerraceRouteImport
      parentRoute: typeof StaysRoute
    }
    '/taisykles/$': {
      id: '/taisykles/$'
      path: '/taisykles/$'
      fullPath: '/taisykles/$'
      preLoaderRoute: typeof TaisyklesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contracts': {
      id: '/_authenticated/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AuthenticatedAdminContractsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/expenses': {
      id: '/_authenticated/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AuthenticatedAdminExpensesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/housekeeping': {
      id: '/_authenticated/admin/housekeeping'
      path: '/housekeeping'
      fullPath: '/admin/housekeeping'
      preLoaderRoute: typeof AuthenticatedAdminHousekeepingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inquiries': {
      id: '/_authenticated/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AuthenticatedAdminInquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/$id': {
      id: '/_authenticated/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AuthenticatedStaffIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/api/assistant/chat': {
      id: '/api/assistant/chat'
      path: '/api/assistant/chat'
      fullPath: '/api/assistant/chat'
      preLoaderRoute: typeof ApiAssistantChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ical-sync': {
      id: '/api/public/ical-sync'
      path: '/api/public/ical-sync'
      fullPath: '/api/public/ical-sync'
      preLoaderRoute: typeof ApiPublicIcalSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications-cron': {
      id: '/api/public/notifications-cron'
      path: '/api/public/notifications-cron'
      fullPath: '/api/public/notifications-cron'
      preLoaderRoute: typeof ApiPublicNotificationsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about/': {
      id: '/en/about/'
      path: '/'
      fullPath: '/en/about/'
      preLoaderRoute: typeof EnAboutIndexRouteImport
      parentRoute: typeof EnAboutRoute
    }
    '/en/about/house-rules': {
      id: '/en/about/house-rules'
      path: '/house-rules'
      fullPath: '/en/about/house-rules'
      preLoaderRoute: typeof EnAboutHouseRulesRouteImport
      parentRoute: typeof EnAboutRoute
    }
    '/en/booking/confirmed': {
      id: '/en/booking/confirmed'
      path: '/booking/confirmed'
      fullPath: '/en/booking/confirmed'
      preLoaderRoute: typeof EnBookingConfirmedRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/stays/': {
      id: '/en/stays/'
      path: '/'
      fullPath: '/en/stays/'
      preLoaderRoute: typeof EnStaysIndexRouteImport
      parentRoute: typeof EnStaysRoute
    }
    '/en/stays/$propertyId': {
      id: '/en/stays/$propertyId'
      path: '/$propertyId'
      fullPath: '/en/stays/$propertyId'
      preLoaderRoute: typeof EnStaysPropertyIdRouteImport
      parentRoute: typeof EnStaysRoute
    }
    '/en/stays/standard': {
      id: '/en/stays/standard'
      path: '/standard'
      fullPath: '/en/stays/standard'
      preLoaderRoute: typeof EnStaysStandardRouteImport
      parentRoute: typeof EnStaysRoute
    }
    '/en/stays/with-terrace': {
      id: '/en/stays/with-terrace'
      path: '/with-terrace'
      fullPath: '/en/stays/with-terrace'
      preLoaderRoute: typeof EnStaysWithTerraceRouteImport
      parentRoute: typeof EnStaysRoute
    }
    '/stays/type/$categorySlug': {
      id: '/stays/type/$categorySlug'
      path: '/type/$categorySlug'
      fullPath: '/stays/type/$categorySlug'
      preLoaderRoute: typeof StaysTypeCategorySlugRouteImport
      parentRoute: typeof StaysRoute
    }
    '/_authenticated/admin/bookings/': {
      id: '/_authenticated/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings/$id': {
      id: '/_authenticated/admin/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings/new': {
      id: '/_authenticated/admin/bookings/new'
      path: '/bookings/new'
      fullPath: '/admin/bookings/new'
      preLoaderRoute: typeof AuthenticatedAdminBookingsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties/': {
      id: '/_authenticated/admin/properties/'
      path: '/properties'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties/new': {
      id: '/_authenticated/admin/properties/new'
      path: '/properties/new'
      fullPath: '/admin/properties/new'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/v1/availability': {
      id: '/api/public/v1/availability'
      path: '/api/public/v1/availability'
      fullPath: '/api/public/v1/availability'
      preLoaderRoute: typeof ApiPublicV1AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/bookings': {
      id: '/api/public/v1/bookings'
      path: '/api/public/v1/bookings'
      fullPath: '/api/public/v1/bookings'
      preLoaderRoute: typeof ApiPublicV1BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/legal': {
      id: '/api/public/v1/legal'
      path: '/api/public/v1/legal'
      fullPath: '/api/public/v1/legal'
      preLoaderRoute: typeof ApiPublicV1LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/payment-details': {
      id: '/api/public/v1/payment-details'
      path: '/api/public/v1/payment-details'
      fullPath: '/api/public/v1/payment-details'
      preLoaderRoute: typeof ApiPublicV1PaymentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/properties': {
      id: '/api/public/v1/properties'
      path: '/api/public/v1/properties'
      fullPath: '/api/public/v1/properties'
      preLoaderRoute: typeof ApiPublicV1PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/quote': {
      id: '/api/public/v1/quote'
      path: '/api/public/v1/quote'
      fullPath: '/api/public/v1/quote'
      preLoaderRoute: typeof ApiPublicV1QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/v1/rooms': {
      id: '/api/staff/v1/rooms'
      path: '/api/staff/v1/rooms'
      fullPath: '/api/staff/v1/rooms'
      preLoaderRoute: typeof ApiStaffV1RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/stays/type/$categorySlug': {
      id: '/en/stays/type/$categorySlug'
      path: '/type/$categorySlug'
      fullPath: '/en/stays/type/$categorySlug'
      preLoaderRoute: typeof EnStaysTypeCategorySlugRouteImport
      parentRoute: typeof EnStaysRoute
    }
    '/_authenticated/admin/properties/$id/edit': {
      id: '/_authenticated/admin/properties/$id/edit'
      path: '/properties/$id/edit'
      fullPath: '/admin/properties/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/v1/bookings/$bookingNumber': {
      id: '/api/public/v1/bookings/$bookingNumber'
      path: '/$bookingNumber'
      fullPath: '/api/public/v1/bookings/$bookingNumber'
      preLoaderRoute: typeof ApiPublicV1BookingsBookingNumberRouteImport
      parentRoute: typeof ApiPublicV1BookingsRoute
    }
    '/api/public/v1/properties/$id': {
      id: '/api/public/v1/properties/$id'
      path: '/$id'
      fullPath: '/api/public/v1/properties/$id'
      preLoaderRoute: typeof ApiPublicV1PropertiesIdRouteImport
      parentRoute: typeof ApiPublicV1PropertiesRoute
    }
    '/api/staff/v1/rooms/$id/assign': {
      id: '/api/staff/v1/rooms/$id/assign'
      path: '/$id/assign'
      fullPath: '/api/staff/v1/rooms/$id/assign'
      preLoaderRoute: typeof ApiStaffV1RoomsIdAssignRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
    '/api/staff/v1/rooms/$id/comments': {
      id: '/api/staff/v1/rooms/$id/comments'
      path: '/$id/comments'
      fullPath: '/api/staff/v1/rooms/$id/comments'
      preLoaderRoute: typeof ApiStaffV1RoomsIdCommentsRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
    '/api/staff/v1/rooms/$id/issue': {
      id: '/api/staff/v1/rooms/$id/issue'
      path: '/$id/issue'
      fullPath: '/api/staff/v1/rooms/$id/issue'
      preLoaderRoute: typeof ApiStaffV1RoomsIdIssueRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
    '/api/staff/v1/rooms/$id/status': {
      id: '/api/staff/v1/rooms/$id/status'
      path: '/$id/status'
      fullPath: '/api/staff/v1/rooms/$id/status'
      preLoaderRoute: typeof ApiStaffV1RoomsIdStatusRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
    '/api/staff/v1/rooms/$id/unassign': {
      id: '/api/staff/v1/rooms/$id/unassign'
      path: '/$id/unassign'
      fullPath: '/api/staff/v1/rooms/$id/unassign'
      preLoaderRoute: typeof ApiStaffV1RoomsIdUnassignRouteImport
      parentRoute: typeof ApiStaffV1RoomsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminContractsRoute: typeof AuthenticatedAdminContractsRoute
  AuthenticatedAdminExpensesRoute: typeof AuthenticatedAdminExpensesRoute
  AuthenticatedAdminHousekeepingRoute: typeof AuthenticatedAdminHousekeepingRoute
  AuthenticatedAdminInquiriesRoute: typeof AuthenticatedAdminInquiriesRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBookingsIdRoute: typeof AuthenticatedAdminBookingsIdRoute
  AuthenticatedAdminBookingsNewRoute: typeof AuthenticatedAdminBookingsNewRoute
  AuthenticatedAdminPropertiesNewRoute: typeof AuthenticatedAdminPropertiesNewRoute
  AuthenticatedAdminBookingsIndexRoute: typeof AuthenticatedAdminBookingsIndexRoute
  AuthenticatedAdminPropertiesIndexRoute: typeof AuthenticatedAdminPropertiesIndexRoute
  AuthenticatedAdminPropertiesIdEditRoute: typeof AuthenticatedAdminPropertiesIdEditRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminContractsRoute: AuthenticatedAdminContractsRoute,
  AuthenticatedAdminExpensesRoute: AuthenticatedAdminExpensesRoute,
  AuthenticatedAdminHousekeepingRoute: AuthenticatedAdminHousekeepingRoute,
  AuthenticatedAdminInquiriesRoute: AuthenticatedAdminInquiriesRoute,
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBookingsIdRoute: AuthenticatedAdminBookingsIdRoute,
  AuthenticatedAdminBookingsNewRoute: AuthenticatedAdminBookingsNewRoute,
  AuthenticatedAdminPropertiesNewRoute: AuthenticatedAdminPropertiesNewRoute,
  AuthenticatedAdminBookingsIndexRoute: AuthenticatedAdminBookingsIndexRoute,
  AuthenticatedAdminPropertiesIndexRoute:
    AuthenticatedAdminPropertiesIndexRoute,
  AuthenticatedAdminPropertiesIdEditRoute:
    AuthenticatedAdminPropertiesIdEditRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffIdRoute: typeof AuthenticatedStaffIdRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffIdRoute: AuthenticatedStaffIdRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EnAboutRouteChildren {
  EnAboutHouseRulesRoute: typeof EnAboutHouseRulesRoute
  EnAboutIndexRoute: typeof EnAboutIndexRoute
}

const EnAboutRouteChildren: EnAboutRouteChildren = {
  EnAboutHouseRulesRoute: EnAboutHouseRulesRoute,
  EnAboutIndexRoute: EnAboutIndexRoute,
}

const EnAboutRouteWithChildren =
  EnAboutRoute._addFileChildren(EnAboutRouteChildren)

interface EnStaysRouteChildren {
  EnStaysPropertyIdRoute: typeof EnStaysPropertyIdRoute
  EnStaysStandardRoute: typeof EnStaysStandardRoute
  EnStaysWithTerraceRoute: typeof EnStaysWithTerraceRoute
  EnStaysIndexRoute: typeof EnStaysIndexRoute
  EnStaysTypeCategorySlugRoute: typeof EnStaysTypeCategorySlugRoute
}

const EnStaysRouteChildren: EnStaysRouteChildren = {
  EnStaysPropertyIdRoute: EnStaysPropertyIdRoute,
  EnStaysStandardRoute: EnStaysStandardRoute,
  EnStaysWithTerraceRoute: EnStaysWithTerraceRoute,
  EnStaysIndexRoute: EnStaysIndexRoute,
  EnStaysTypeCategorySlugRoute: EnStaysTypeCategorySlugRoute,
}

const EnStaysRouteWithChildren =
  EnStaysRoute._addFileChildren(EnStaysRouteChildren)

interface EnRouteRouteChildren {
  EnAboutRoute: typeof EnAboutRouteWithChildren
  EnAvailabilityRoute: typeof EnAvailabilityRoute
  EnBanquetHallRoute: typeof EnBanquetHallRoute
  EnCabinRoute: typeof EnCabinRoute
  EnContactRoute: typeof EnContactRoute
  EnGiftVouchersRoute: typeof EnGiftVouchersRoute
  EnHomeV2Route: typeof EnHomeV2Route
  EnPrivacyPolicyRoute: typeof EnPrivacyPolicyRoute
  EnRestaurantRoute: typeof EnRestaurantRoute
  EnSaunaRoute: typeof EnSaunaRoute
  EnStaysRoute: typeof EnStaysRouteWithChildren
  EnTermsRoute: typeof EnTermsRoute
  EnIndexRoute: typeof EnIndexRoute
  EnBookingConfirmedRoute: typeof EnBookingConfirmedRoute
}

const EnRouteRouteChildren: EnRouteRouteChildren = {
  EnAboutRoute: EnAboutRouteWithChildren,
  EnAvailabilityRoute: EnAvailabilityRoute,
  EnBanquetHallRoute: EnBanquetHallRoute,
  EnCabinRoute: EnCabinRoute,
  EnContactRoute: EnContactRoute,
  EnGiftVouchersRoute: EnGiftVouchersRoute,
  EnHomeV2Route: EnHomeV2Route,
  EnPrivacyPolicyRoute: EnPrivacyPolicyRoute,
  EnRestaurantRoute: EnRestaurantRoute,
  EnSaunaRoute: EnSaunaRoute,
  EnStaysRoute: EnStaysRouteWithChildren,
  EnTermsRoute: EnTermsRoute,
  EnIndexRoute: EnIndexRoute,
  EnBookingConfirmedRoute: EnBookingConfirmedRoute,
}

const EnRouteRouteWithChildren =
  EnRouteRoute._addFileChildren(EnRouteRouteChildren)

interface AboutRouteChildren {
  AboutHouseRulesRoute: typeof AboutHouseRulesRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutHouseRulesRoute: AboutHouseRulesRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface StaysRouteChildren {
  StaysPropertyIdRoute: typeof StaysPropertyIdRoute
  StaysStandardRoute: typeof StaysStandardRoute
  StaysWithTerraceRoute: typeof StaysWithTerraceRoute
  StaysIndexRoute: typeof StaysIndexRoute
  StaysTypeCategorySlugRoute: typeof StaysTypeCategorySlugRoute
}

const StaysRouteChildren: StaysRouteChildren = {
  StaysPropertyIdRoute: StaysPropertyIdRoute,
  StaysStandardRoute: StaysStandardRoute,
  StaysWithTerraceRoute: StaysWithTerraceRoute,
  StaysIndexRoute: StaysIndexRoute,
  StaysTypeCategorySlugRoute: StaysTypeCategorySlugRoute,
}

const StaysRouteWithChildren = StaysRoute._addFileChildren(StaysRouteChildren)

interface ApiPublicV1BookingsRouteChildren {
  ApiPublicV1BookingsBookingNumberRoute: typeof ApiPublicV1BookingsBookingNumberRoute
}

const ApiPublicV1BookingsRouteChildren: ApiPublicV1BookingsRouteChildren = {
  ApiPublicV1BookingsBookingNumberRoute: ApiPublicV1BookingsBookingNumberRoute,
}

const ApiPublicV1BookingsRouteWithChildren =
  ApiPublicV1BookingsRoute._addFileChildren(ApiPublicV1BookingsRouteChildren)

interface ApiPublicV1PropertiesRouteChildren {
  ApiPublicV1PropertiesIdRoute: typeof ApiPublicV1PropertiesIdRoute
}

const ApiPublicV1PropertiesRouteChildren: ApiPublicV1PropertiesRouteChildren = {
  ApiPublicV1PropertiesIdRoute: ApiPublicV1PropertiesIdRoute,
}

const ApiPublicV1PropertiesRouteWithChildren =
  ApiPublicV1PropertiesRoute._addFileChildren(
    ApiPublicV1PropertiesRouteChildren,
  )

interface ApiStaffV1RoomsRouteChildren {
  ApiStaffV1RoomsIdAssignRoute: typeof ApiStaffV1RoomsIdAssignRoute
  ApiStaffV1RoomsIdCommentsRoute: typeof ApiStaffV1RoomsIdCommentsRoute
  ApiStaffV1RoomsIdIssueRoute: typeof ApiStaffV1RoomsIdIssueRoute
  ApiStaffV1RoomsIdStatusRoute: typeof ApiStaffV1RoomsIdStatusRoute
  ApiStaffV1RoomsIdUnassignRoute: typeof ApiStaffV1RoomsIdUnassignRoute
}

const ApiStaffV1RoomsRouteChildren: ApiStaffV1RoomsRouteChildren = {
  ApiStaffV1RoomsIdAssignRoute: ApiStaffV1RoomsIdAssignRoute,
  ApiStaffV1RoomsIdCommentsRoute: ApiStaffV1RoomsIdCommentsRoute,
  ApiStaffV1RoomsIdIssueRoute: ApiStaffV1RoomsIdIssueRoute,
  ApiStaffV1RoomsIdStatusRoute: ApiStaffV1RoomsIdStatusRoute,
  ApiStaffV1RoomsIdUnassignRoute: ApiStaffV1RoomsIdUnassignRoute,
}

const ApiStaffV1RoomsRouteWithChildren = ApiStaffV1RoomsRoute._addFileChildren(
  ApiStaffV1RoomsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EnRouteRoute: EnRouteRouteWithChildren,
  AboutRoute: AboutRouteWithChildren,
  AuthRoute: AuthRoute,
  AvailabilityRoute: AvailabilityRoute,
  BanquetHallRoute: BanquetHallRoute,
  CabinRoute: CabinRoute,
  ContactRoute: ContactRoute,
  GiftVouchersRoute: GiftVouchersRoute,
  HomeV2Route: HomeV2Route,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantRoute: RestaurantRoute,
  SaunaRoute: SaunaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaysRoute: StaysRouteWithChildren,
  TermsRoute: TermsRoute,
  ApartamentaiSplatRoute: ApartamentaiSplatRoute,
  ApiTrackViewRoute: ApiTrackViewRoute,
  ApieSplatRoute: ApieSplatRoute,
  BanketineSaleSplatRoute: BanketineSaleSplatRoute,
  BookingConfirmedRoute: BookingConfirmedRoute,
  DovanuKuponaiSplatRoute: DovanuKuponaiSplatRoute,
  KontaktaiSplatRoute: KontaktaiSplatRoute,
  LaisviKambariaiSplatRoute: LaisviKambariaiSplatRoute,
  NamelisSplatRoute: NamelisSplatRoute,
  PrivatumoPolitikaSplatRoute: PrivatumoPolitikaSplatRoute,
  RestobarasSplatRoute: RestobarasSplatRoute,
  RezervacijaSplatRoute: RezervacijaSplatRoute,
  TaisyklesSplatRoute: TaisyklesSplatRoute,
  ApiAssistantChatRoute: ApiAssistantChatRoute,
  ApiPublicIcalSyncRoute: ApiPublicIcalSyncRoute,
  ApiPublicNotificationsCronRoute: ApiPublicNotificationsCronRoute,
  ApiPublicV1AvailabilityRoute: ApiPublicV1AvailabilityRoute,
  ApiPublicV1BookingsRoute: ApiPublicV1BookingsRouteWithChildren,
  ApiPublicV1LegalRoute: ApiPublicV1LegalRoute,
  ApiPublicV1PaymentDetailsRoute: ApiPublicV1PaymentDetailsRoute,
  ApiPublicV1PropertiesRoute: ApiPublicV1PropertiesRouteWithChildren,
  ApiPublicV1QuoteRoute: ApiPublicV1QuoteRoute,
  ApiStaffV1RoomsRoute: ApiStaffV1RoomsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
